// frontend/src/app/features/expenses/attachments-modal/attachments-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AttachmentService } from '../../../core/services/attachment.service';
import { Attachment } from '../../../core/models/attachment.model';

@Component({
  selector: 'app-attachments-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
         (click)="onBackdrop($event)">
      <div class="bg-gray-900 border border-gray-700 rounded-2xl shadow-2xl w-full max-w-md"
           (click)="$event.stopPropagation()">

        <!-- Header -->
        <div class="flex items-center justify-between px-5 py-4 border-b border-gray-800">
          <h2 class="text-base font-semibold text-white">Adjuntos</h2>
          <button (click)="close.emit()"
                  class="w-8 h-8 flex items-center justify-center rounded-lg text-gray-400 hover:text-white hover:bg-gray-800 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="p-5">
          <div *ngIf="loading" class="py-8 text-center text-gray-500 text-sm">Cargando...</div>

          <div *ngIf="!loading && attachments.length === 0" class="py-8 text-center">
            <svg class="w-10 h-10 text-gray-700 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/>
            </svg>
            <p class="text-gray-500 text-sm">Sin adjuntos</p>
          </div>

          <ul *ngIf="!loading && attachments.length > 0" class="space-y-2">
            <li *ngFor="let a of attachments"
                class="flex items-center gap-3 p-3 rounded-xl bg-gray-800/60 border border-gray-700/50">

              <!-- Thumbnail o ícono -->
              <div class="w-10 h-10 rounded-lg overflow-hidden shrink-0 bg-gray-700 flex items-center justify-center"
                   [class.cursor-pointer]="isImage(a) && thumbnails[a.id]"
                   (click)="isImage(a) && thumbnails[a.id] ? openLightbox(thumbnails[a.id], a.fileName) : null">
                <img *ngIf="isImage(a) && thumbnails[a.id]" [src]="thumbnails[a.id]"
                     class="w-full h-full object-cover" [alt]="a.fileName">
                <svg *ngIf="!isImage(a) || !thumbnails[a.id]"
                     class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                    d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
                </svg>
              </div>

              <!-- Info -->
              <div class="flex-1 min-w-0">
                <p class="text-sm text-gray-200 truncate font-medium">{{ a.fileName }}</p>
                <p class="text-xs text-gray-500">{{ formatSize(a.fileSize) }}</p>
              </div>

              <!-- Acciones -->
              <div class="flex gap-1 shrink-0">
                <button (click)="download(a)"
                        class="w-8 h-8 flex items-center justify-center rounded-lg text-gray-400 hover:text-blue-400 hover:bg-gray-700 transition-colors"
                        title="Descargar">
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                  </svg>
                </button>
                <button (click)="remove(a)"
                        class="w-8 h-8 flex items-center justify-center rounded-lg text-gray-400 hover:text-red-400 hover:bg-gray-700 transition-colors"
                        title="Eliminar">
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                  </svg>
                </button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Lightbox -->
    <div *ngIf="lightboxUrl"
         class="fixed inset-0 z-[60] flex items-center justify-center bg-black/90"
         (click)="lightboxUrl = null">
      <button class="absolute top-4 right-4 w-10 h-10 flex items-center justify-center rounded-full bg-gray-800 text-gray-300 hover:text-white hover:bg-gray-700 transition-colors"
              (click)="lightboxUrl = null">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
        </svg>
      </button>
      <img [src]="lightboxUrl" [alt]="lightboxAlt"
           class="max-w-[90vw] max-h-[90vh] rounded-xl object-contain shadow-2xl"
           (click)="$event.stopPropagation()">
    </div>
  `
})
export class AttachmentsModalComponent implements OnInit {
  @Input() expenseId!: number;
  @Output() close = new EventEmitter<void>();
  @Output() countChanged = new EventEmitter<number>();

  private readonly attachmentService = inject(AttachmentService);

  attachments: Attachment[] = [];
  loading = false;
  thumbnails: Record<number, string> = {};
  lightboxUrl: string | null = null;
  lightboxAlt = '';

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.attachmentService.getAll(this.expenseId).subscribe({
      next: list => {
        this.attachments = list;
        this.loading = false;
        list.filter(a => this.isImage(a)).forEach(a => this.loadThumbnail(a));
      },
      error: () => { this.loading = false; }
    });
  }

  loadThumbnail(a: Attachment): void {
    this.attachmentService.presignDownload(this.expenseId, a.id).subscribe(url => {
      this.thumbnails[a.id] = url;
    });
  }

  download(a: Attachment): void {
    this.attachmentService.presignDownload(this.expenseId, a.id).subscribe(url => {
      const link = document.createElement('a');
      link.href = url;
      link.download = a.fileName;
      link.click();
    });
  }

  remove(a: Attachment): void {
    if (!confirm(`¿Eliminar "${a.fileName}"?`)) return;
    this.attachmentService.delete(this.expenseId, a.id).subscribe(() => {
      this.attachments = this.attachments.filter(x => x.id !== a.id);
      this.countChanged.emit(this.attachments.length);
    });
  }

  openLightbox(url: string, fileName: string): void {
    this.lightboxUrl = url;
    this.lightboxAlt = fileName;
  }

  isImage(a: Attachment): boolean {
    return a.contentType.startsWith('image/');
  }

  formatSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1_048_576) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / 1_048_576).toFixed(1) + ' MB';
  }

  onBackdrop(event: MouseEvent): void {
    this.close.emit();
  }
}

// frontend-next/src/components/features/expenses/AttachmentsModal.tsx
'use client'

import { useEffect, useState } from 'react'

import { motion } from 'framer-motion'

import { getDownloadUrl } from '@/lib/api/attachments'
import { useAttachments } from '@/lib/hooks/useAttachments'
import type { Attachment } from '@/types'

function formatSize(bytes: number) {
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function AttachmentPreview({ attachment: a, expenseId }: { attachment: Attachment; expenseId: number }) {
  const isImage = a.contentType.startsWith('image/')
  const [url, setUrl] = useState<string | null>(null)

  useEffect(() => {
    getDownloadUrl(expenseId, a.id).then(setUrl).catch(() => {})
  }, [expenseId, a.id])

  return (
    <div className="flex flex-col overflow-hidden rounded-[14px] border" style={{ borderColor: 'var(--border-subtle)', background: 'var(--bg-card-inner)' }}>
      {isImage ? (
        <div className="flex h-36 items-center justify-center" style={{ background: 'var(--bg-input)' }}>
          {url
            ? <img src={url} alt={a.fileName} className="h-full w-full object-contain" />
            : <div className="h-6 w-6 animate-pulse rounded-full" style={{ background: 'var(--border-subtle)' }} />
          }
        </div>
      ) : (
        <div className="flex h-36 items-center justify-center" style={{ background: 'var(--bg-input)' }}>
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{ color: 'var(--text-muted)' }}>
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
            <polyline points="14 2 14 8 20 8"/>
            <line x1="9" y1="13" x2="15" y2="13"/>
            <line x1="9" y1="17" x2="15" y2="17"/>
          </svg>
        </div>
      )}
      <div className="flex items-center justify-between gap-2 px-3 py-2">
        <div className="min-w-0">
          <p className="truncate text-[11px] font-medium" style={{ color: 'var(--text-primary)' }}>{a.fileName}</p>
          <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{formatSize(a.fileSize)}</p>
        </div>
        {url && (
          <a
            href={url}
            target="_blank"
            rel="noopener noreferrer"
            className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-lg transition-colors"
            style={{ color: 'var(--text-muted)' }}
            onMouseEnter={e => { e.currentTarget.style.background = 'var(--bg-hover)'; e.currentTarget.style.color = 'var(--text-primary)' }}
            onMouseLeave={e => { e.currentTarget.style.background = ''; e.currentTarget.style.color = 'var(--text-muted)' }}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
              <polyline points="7 10 12 15 17 10"/>
              <line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
          </a>
        )}
      </div>
    </div>
  )
}

interface AttachmentsModalProps {
  expenseId: number
  description: string
  onClose: () => void
}

export function AttachmentsModal({ expenseId, description, onClose }: AttachmentsModalProps) {
  const { data: attachments = [], isLoading } = useAttachments(expenseId)

  useEffect(() => {
    function onKey(e: KeyboardEvent) { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.15 }}
        className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"
        style={{ background: 'rgba(0,0,0,0.5)' }}
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 24 }}
          transition={{ duration: 0.2, ease: [0.32, 0.72, 0, 1] }}
          className="w-full max-w-sm overflow-hidden rounded-t-[24px] sm:max-w-2xl sm:rounded-[20px]"
          style={{ background: 'var(--bg-card-inner)', maxHeight: '85dvh' }}
          onClick={e => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b px-4 py-4" style={{ borderColor: 'var(--border-subtle)' }}>
            <div>
              <p className="text-[13px] font-bold" style={{ color: 'var(--text-primary)' }}>Adjuntos</p>
              <p className="truncate text-[11px]" style={{ color: 'var(--text-muted)', maxWidth: '200px' }}>{description}</p>
            </div>
            <button
              onClick={onClose}
              className="flex h-7 w-7 items-center justify-center rounded-full cursor-pointer"
              style={{ background: 'var(--bg-hover)', color: 'var(--text-muted)' }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
              </svg>
            </button>
          </div>

          {/* Content */}
          <div className="overflow-y-auto p-4" style={{ maxHeight: 'calc(85dvh - 60px)' }}>
            {isLoading ? (
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                {[1, 2].map(i => (
                  <div key={i} className="h-48 animate-pulse rounded-[14px]" style={{ background: 'var(--bg-hover)' }} />
                ))}
              </div>
            ) : attachments.length === 0 ? (
              <p className="py-6 text-center text-[12px]" style={{ color: 'var(--text-muted)' }}>Sin adjuntos</p>
            ) : (
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                {attachments.map(a => (
                  <AttachmentPreview key={a.id} attachment={a} expenseId={expenseId} />
                ))}
              </div>
            )}
          </div>
        </motion.div>
      </motion.div>
  )
}
